//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCarousell_P.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteractiveCarousell_P.Resources.Localization.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Roman pasta dish
        ///1 tablespoon extra virgin olive oil or unsalted butter
        ///1/2 pound pancetta or thick cut bacon, diced
        ///1 to 2 garlic cloves, minced, about 1 teaspoon (optional)
        ///3 to 4 whole eggs
        ///1 cup grated Parmesan or pecorino cheese
        ///1 pound spaghetti (or bucatini or fettuccine)
        ///Kosher salt and freshly ground black pepper to taste.
        /// </summary>
        internal static string CarbonaraDescription {
            get {
                return ResourceManager.GetString("CarbonaraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        internal static string EstonianButton {
            get {
                return ResourceManager.GetString("EstonianButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Layers of pasta, meat, and cheese
        ///2 olive oil
        ///plus extra for the dish
        ///750g lean beef mince
        ///90g pack prosciutto
        ///800g passata or half our basic tomato sauce
        ///200ml hot beef stock
        ///nutmeg
        ///300g fresh lasagne sheets
        ///white sauce
        ///(find a recipe in the method, or use shop-bought)
        ///125g ball mozzarella
        ///torn into thin strips.
        /// </summary>
        internal static string LasagneDescription {
            get {
                return ResourceManager.GetString("LasagneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and delicious
        ///16 ounces pizza dough, store-bought or homemade (I like this no-knead version, though note that this recipe makes enough dough for 2 pizzas)
        ///1/2 cup pizza sauce (see below)
        ///18 to 20 slices pepperoni
        ///12 ounces mozzarella cheese, grated
        ///1/2 teaspoon ground black pepper
        ///1 teaspoon fresh oregano, optional
        ///Flour for rolling and shaping dough.
        /// </summary>
        internal static string PizzaDescription {
            get {
                return ResourceManager.GetString("PizzaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creamy saffron rice 
        ///1 supilusikatäis võid
        ///3 supilusikatäit oliiviõli
        ///
        ///1 väike sibul, hakitud (umbes 1 tass)
        ///
        ///2 tassi aborio või muud lühikese kuni keskmise teraga riisi
        ///
        ///½ tassi valget veini
        ///
        ///6–8 tassi kuumutatud kanapuljongit
        ///
        ///¼ tassi riivitud Parmesani juustu
        ///
        ///1 ½ supilusikatäit võid või oliiviõli viimistlemiseks
        ///
        ///Väike peotäis hakitud peterselli
        ///
        ///Soola, pipart.
        /// </summary>
        internal static string RisottoDescription {
            get {
                return ResourceManager.GetString("RisottoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Popular coffee-flavored dessert
        ///Mascarpone cheese and heavy cream – They create the tiramisu’s rich, creamy layers.
        ///Granulated sugar and vanilla extract – They flavor the cream. For the best texture, use a fine white granulated sugar for this recipe, not natural cane sugar. I also tested this recipe with powdered sugar. It worked fine, but granulated sugar gives the cream a smoother texture.
        ///Ladyfingers – You’ll soak these Italian cookies in espresso to create the non-cream layers of the tiramisu. They’ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TiramisuDescription {
            get {
                return ResourceManager.GetString("TiramisuDescription", resourceCulture);
            }
        }
    }
}
